import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import PropTypes from "prop-types";

import { SaisonProvider } from "./context/SaisonContext";


RootLayout.propTypes = {
  children: PropTypes.node,
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <SaisonProvider>
          {children}
        </SaisonProvider>
      </body>
    </html>
  );
}
