export const SAISONS = {
  printemps: {
    nom: "Printemps",
    fondPage: "#F9FAF4",
    textePrincipal: "#111827",
    texteSecondaire: "#6B7280",
    boutonPrincipalFond: "#A2D39C",
    boutonPrincipalTexte: "#111827",
    boutonSecondaireFond: "#F5D7E3",
    boutonSecondaireTexte: "#111827",
    badgeFond: "#FFFA9C",
    badgeTexte: "#111827",
  },
  ete: {
  nom: "Été",
  fondPage: "#FDF6EC",
  textePrincipal: "#2C2420",
  texteSecondaire: "#7A6A60",
  boutonPrincipalFond: "#3A9BD5",    // ✅ bleu pour BoutonAction
  boutonPrincipalTexte: "#FFFFFF",
  boutonSecondaireFond: "#F2C46D",   // ✅ jaune pour les items du menu
  boutonSecondaireTexte: "#2C2420",  // ← texte foncé sur jaune
  badgeFond: "#F2C46D",
  badgeTexte: "#2C2420",
},
  automne: {
    nom: "Automne",
    fondPage: "#FAF3E8",
    textePrincipal: "#2A1F14",
    texteSecondaire: "#7A5C3E",
    boutonPrincipalFond: "#C0622A",
    boutonPrincipalTexte: "#FFFFFF",
    boutonSecondaireFond: "#6B7C4E",
    boutonSecondaireTexte: "#FFFFFF",
    badgeFond: "#D4A843",
    badgeTexte: "#2A1F14",
  },
  hiver: {
    nom: "Hiver",
    fondPage: "#F0F4F8",
    textePrincipal: "#1E2A3A",
    texteSecondaire: "#5E7087",
    boutonPrincipalFond: "#5BA4CF",
    boutonPrincipalTexte: "#FFFFFF",
    boutonSecondaireFond: "#9B8EC4",
    boutonSecondaireTexte: "#FFFFFF",
    badgeFond: "#2E4A6A",
    badgeTexte: "#F0F4F8",
  },
};
